export const USER_REPOSITORY = "USER_REPOSITORY";
export const HASH_SERVICE = "HASH_SERVICE";
export const RESTAURANTE_REPOSITORY = "RESTAURANTE_REPOSITORY";
export const MESA_REPOSITORY = "MESA_REPOSITORY";
export const PRODUCTO_REPOSITORY = "PRODUCTO_REPOSITORY";
export const TIPO_PRODUCTO_REPOSITORY = "TIPO_PRODUCTO_REPOSITORY";
export const PEDIDO_REPOSITORY = "PEDIDO_REPOSITORY";
export const DETALLE_PEDIDO_REPOSITORY = "DETALLE_PEDIDO_REPOSITORY";
